apiVersion: v1
kind: Service
metadata:
  name: llm-code-generator
spec:
  type: NodePort
  selector:
    app: llm-code-generator
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
